"""VBA source code for the Tabella field entry workbook macro.

V1 layout preserved (headers row 1, data row 2).
Added: Records sheet integration for personal/commercial/specimen history.
Added: RefreshRecords sub that shells out to Python.
"""

THISWORKBOOK_CODE = (
    "Private Sub Workbook_SheetChange(ByVal Sh As Object, ByVal Target As Range)\r\n"
    "    On Error Resume Next\r\n"
    "    Application.EnableEvents = False\r\n"
    "    DataEntry.OnSpeciesChanged Target\r\n"
    "    Application.EnableEvents = True\r\n"
    "    On Error GoTo 0\r\n"
    "End Sub\r\n"
    "\r\n"
    "Private Sub Workbook_SheetSelectionChange(ByVal Sh As Object, ByVal Target As Range)\r\n"
    "    On Error Resume Next\r\n"
    "    DataEntry.OnSelectionChanged Target\r\n"
    "    On Error GoTo 0\r\n"
    "End Sub\r\n"
)

MODULE_CODE = (
    "Option Explicit\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' DataEntry -- Auto-populates taxonomy, conservation, and\r\n"
    "' recording history from UKSI + Records sheets.\r\n"
    "' Now includes pending counts from active workbooks.\r\n"
    "' =============================================================\r\n"
    "\r\n"
    "' -- Cached UKSI data (fixed layout: cols A-N) --\r\n"
    "Private pData As Variant\r\n"
    "Private pLoaded As Boolean\r\n"
    "Private pRows As Long\r\n"
    "\r\n"
    "' -- Row layout constants --\r\n"
    "Private Const HDR_ROW    As Long = 4\r\n"
    "Private Const DATA_START As Long = 5\r\n"
    "\r\n"
    "' -- Cached Records data (dictionary: TVK -> array) --\r\n"
    "Private pRec As Object\r\n"
    "Private pRecLoaded As Boolean\r\n"
    "\r\n"
    "' -- Cached own-workbook pending counts (dictionary: TVK -> array) --\r\n"
    "Private pOwn As Object\r\n"
    "Private pOwnLoaded As Boolean\r\n"
    "\r\n"
    "' -- UKSI array column indices (fixed A-N) --\r\n"
    "Private Const U_NAME    As Long = 1\r\n"
    "Private Const U_TVK     As Long = 2\r\n"
    "Private Const U_COMMON  As Long = 3\r\n"
    "Private Const U_CLASS   As Long = 4\r\n"
    "Private Const U_FAMILY  As Long = 5\r\n"
    "Private Const U_ORDER   As Long = 6\r\n"
    "Private Const U_CONSERV As Long = 7\r\n"
    "Private Const U_REDLIST As Long = 8\r\n"
    "Private Const U_RARITY  As Long = 9\r\n"
    "Private Const U_S41     As Long = 10\r\n"
    "Private Const U_LEGAL   As Long = 11\r\n"
    "Private Const U_BAP     As Long = 12\r\n"
    "Private Const U_SORT    As Long = 13\r\n"
    "\r\n"
    "' -- Cached header maps per sheet --\r\n"
    "Private pCache As Object\r\n"
    "\r\n"
    "' -- Header names the macro looks for --\r\n"
    "Private Const H_SPECIES     As String = \"Species\"\r\n"
    "Private Const H_CONSERV     As String = \"Conservation\"\r\n"
    "Private Const H_REDLIST     As String = \"Red List\"\r\n"
    "Private Const H_RARITY      As String = \"Rarity\"\r\n"
    "Private Const H_S41         As String = \"S41\"\r\n"
    "Private Const H_LEGAL       As String = \"Legal Protection\"\r\n"
    "Private Const H_BAP         As String = \"BAP\"\r\n"
    "Private Const H_TVK         As String = \"TVK\"\r\n"
    "Private Const H_COMMON      As String = \"Common Name\"\r\n"
    "Private Const H_CLASS       As String = \"Class\"\r\n"
    "Private Const H_ORDER       As String = \"Order\"\r\n"
    "Private Const H_FAMILY      As String = \"Family\"\r\n"
    "Private Const H_SORT        As String = \"Sort Code\"\r\n"
    "Private Const H_PERSONAL    As String = \"Personal\"\r\n"
    "Private Const H_COMMERCIAL  As String = \"Commercial\"\r\n"
    "Private Const H_SPECIMENS   As String = \"Specimens\"\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' PUBLIC ENTRY POINT\r\n"
    "' =============================================================\r\n"
    "Public Sub OnSpeciesChanged(ByVal Target As Range)\r\n"
    "    Dim ws As Worksheet\r\n"
    "    Dim cols As Object\r\n"
    "    Dim speciesCol As Long\r\n"
    "    Dim cell As Range\r\n"
    "    Set ws = Target.Worksheet\r\n"
    "    Select Case ws.Name\r\n"
    "        Case \"UKSI\", \"Instructions\", \"Records\"\r\n"
    "            Exit Sub\r\n"
    "    End Select\r\n"
    "    If Not Intersect(Target, ws.Rows(HDR_ROW)) Is Nothing Then\r\n"
    "        If Not pCache Is Nothing Then\r\n"
    "            If pCache.Exists(ws.Name) Then pCache.Remove ws.Name\r\n"
    "        End If\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    Set cols = GetHeaderMap(ws)\r\n"
    "    If cols Is Nothing Then Exit Sub\r\n"
    "    If Not cols.Exists(H_SPECIES) Then Exit Sub\r\n"
    "    speciesCol = cols(H_SPECIES)\r\n"
    "    For Each cell In Target.Cells\r\n"
    "        If cell.Column = speciesCol And cell.Row >= DATA_START Then\r\n"
    "            ProcessCell cell, ws, cols\r\n"
    "        End If\r\n"
    "    Next cell\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' SELECTION CHANGE -- updates info panel (rows 1-3)\r\n"
    "' =============================================================\r\n"
    "Public Sub OnSelectionChanged(ByVal Target As Range)\r\n"
    "    Dim ws As Worksheet\r\n"
    "    Dim cols As Object\r\n"
    "    Set ws = Target.Worksheet\r\n"
    "    Select Case ws.Name\r\n"
    "        Case \"UKSI\", \"Instructions\", \"Records\"\r\n"
    "            Exit Sub\r\n"
    "    End Select\r\n"
    "    If Target.Row < DATA_START Then Exit Sub\r\n"
    "    Set cols = GetHeaderMap(ws)\r\n"
    "    If cols Is Nothing Then Exit Sub\r\n"
    "    UpdateInfoPanel Target.Row, ws, cols\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' INFO PANEL -- writes species summary to rows 1-3\r\n"
    "' =============================================================\r\n"
    "Private Sub UpdateInfoPanel(r As Long, ws As Worksheet, cols As Object)\r\n"
    "    Dim sp As String\r\n"
    "    Dim cn As String\r\n"
    "    Dim fam As String\r\n"
    "    Dim line1 As String\r\n"
    "    Dim parts As String\r\n"
    "    Dim v As String\r\n"
    "    Dim tvk As String\r\n"
    "    Dim dbP As Long\r\n"
    "    Dim dbC As Long\r\n"
    "    Dim dbS As Long\r\n"
    "    Dim pendP As Long\r\n"
    "    Dim pendC As Long\r\n"
    "    Dim rv As Variant\r\n"
    "    Dim ov As Variant\r\n"
    "    Dim rec As String\r\n"
    "    Dim pStr As String\r\n"
    "    Dim comStr As String\r\n"
    "\r\n"
    "    sp = \"\"\r\n"
    "    If cols.Exists(H_SPECIES) Then sp = Trim(CStr(ws.Cells(r, cols(H_SPECIES)).Value))\r\n"
    "    If Len(sp) = 0 Then\r\n"
    "        ws.Cells(1, 1).Value = \"Select a species row to see details here\"\r\n"
    "        ws.Cells(2, 1).Value = \"\"\r\n"
    "        ws.Cells(3, 1).Value = \"\"\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    ' Row 1: Species -- Common Name [Family]\r\n"
    "    cn = \"\"\r\n"
    "    fam = \"\"\r\n"
    "    If cols.Exists(H_COMMON) Then cn = Trim(CStr(ws.Cells(r, cols(H_COMMON)).Value))\r\n"
    "    If cols.Exists(H_FAMILY) Then fam = Trim(CStr(ws.Cells(r, cols(H_FAMILY)).Value))\r\n"
    "    line1 = sp\r\n"
    "    If Len(cn) > 0 Then line1 = line1 & \" -- \" & cn\r\n"
    "    If Len(fam) > 0 Then line1 = line1 & \"  [\" & fam & \"]\"\r\n"
    "    ws.Cells(1, 1).Value = line1\r\n"
    "    ' Row 2: Conservation summary\r\n"
    "    parts = \"\"\r\n"
    "    If cols.Exists(H_RARITY) Then\r\n"
    "        v = Trim(CStr(ws.Cells(r, cols(H_RARITY)).Value))\r\n"
    "        If Len(v) > 0 Then parts = parts & v & \"  \"\r\n"
    "    End If\r\n"
    "    If cols.Exists(H_REDLIST) Then\r\n"
    "        v = Trim(CStr(ws.Cells(r, cols(H_REDLIST)).Value))\r\n"
    "        If Len(v) > 0 Then parts = parts & v & \"  \"\r\n"
    "    End If\r\n"
    "    If cols.Exists(H_S41) Then\r\n"
    "        v = Trim(CStr(ws.Cells(r, cols(H_S41)).Value))\r\n"
    "        If Len(v) > 0 Then parts = parts & \"S41 (\" & v & \")  \"\r\n"
    "    End If\r\n"
    "    If cols.Exists(H_LEGAL) Then\r\n"
    "        v = Trim(CStr(ws.Cells(r, cols(H_LEGAL)).Value))\r\n"
    "        If Len(v) > 0 Then parts = parts & v & \"  \"\r\n"
    "    End If\r\n"
    "    If Len(parts) = 0 Then parts = \"No conservation status\"\r\n"
    "    ws.Cells(2, 1).Value = Trim(parts)\r\n"
    "    ' Row 3: Recording history with pending breakdown\r\n"
    "    tvk = \"\"\r\n"
    "    If cols.Exists(H_TVK) Then tvk = Trim(CStr(ws.Cells(r, cols(H_TVK)).Value))\r\n"
    "    dbP = 0: dbC = 0: dbS = 0: pendP = 0: pendC = 0\r\n"
    "    If Len(tvk) > 0 And tvk <> \"?\" Then\r\n"
    "        If Not pRecLoaded Then LoadRecords\r\n"
    "        If Not pRec Is Nothing Then\r\n"
    "            If pRec.Exists(tvk) Then\r\n"
    "                rv = pRec(tvk)\r\n"
    "                dbP = Val(rv(1))\r\n"
    "                dbC = Val(rv(3))\r\n"
    "                dbS = Val(rv(5))\r\n"
    "                pendP = Val(rv(6))\r\n"
    "                pendC = Val(rv(7))\r\n"
    "            End If\r\n"
    "        End If\r\n"
    "        ' Add own-workbook pending\r\n"
    "        If Not pOwnLoaded Then CountOwnPending\r\n"
    "        If Not pOwn Is Nothing Then\r\n"
    "            If pOwn.Exists(tvk) Then\r\n"
    "                ov = pOwn(tvk)\r\n"
    "                pendP = pendP + Val(ov(1))\r\n"
    "                pendC = pendC + Val(ov(2))\r\n"
    "            End If\r\n"
    "        End If\r\n"
    "    End If\r\n"
    "    pStr = CStr(dbP)\r\n"
    "    If pendP > 0 Then pStr = pStr & \" (+\" & pendP & \"p)\"\r\n"
    "    comStr = CStr(dbC)\r\n"
    "    If pendC > 0 Then comStr = comStr & \" (+\" & pendC & \"p)\"\r\n"
    "    rec = \"Personal: \" & pStr & \"    Commercial: \" & comStr & \"    Specimens: \" & CStr(dbS)\r\n"
    "    ws.Cells(3, 1).Value = rec\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' HEADER SCANNING\r\n"
    "' =============================================================\r\n"
    "Private Function GetHeaderMap(ws As Worksheet) As Object\r\n"
    "    Dim d As Object\r\n"
    "    Dim lastCol As Long\r\n"
    "    Dim c As Long\r\n"
    "    Dim hdr As String\r\n"
    "    If pCache Is Nothing Then Set pCache = CreateObject(\"Scripting.Dictionary\")\r\n"
    "    If pCache.Exists(ws.Name) Then\r\n"
    "        Set GetHeaderMap = pCache(ws.Name)\r\n"
    "        Exit Function\r\n"
    "    End If\r\n"
    "    Set d = CreateObject(\"Scripting.Dictionary\")\r\n"
    "    lastCol = ws.Cells(HDR_ROW, ws.Columns.Count).End(xlToLeft).Column\r\n"
    "    For c = 1 To lastCol\r\n"
    "        hdr = Trim(CStr(ws.Cells(HDR_ROW, c).Value))\r\n"
    "        If Len(hdr) > 0 Then d(hdr) = c\r\n"
    "    Next c\r\n"
    "    If Not d.Exists(H_SPECIES) Or Not d.Exists(H_TVK) Then\r\n"
    "        Set GetHeaderMap = Nothing\r\n"
    "        Exit Function\r\n"
    "    End If\r\n"
    "    Set pCache(ws.Name) = d\r\n"
    "    Set GetHeaderMap = d\r\n"
    "End Function\r\n"
    "\r\n"
    "Public Sub ResetHeaderCache()\r\n"
    "    Set pCache = Nothing\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' CORE LOOKUP\r\n"
    "' =============================================================\r\n"
    "Private Sub ProcessCell(cell As Range, ws As Worksheet, cols As Object)\r\n"
    "    Dim species As String\r\n"
    "    Dim r As Long\r\n"
    "    Dim matches() As Long\r\n"
    "    Dim cnt As Long\r\n"
    "    Dim pick As Long\r\n"
    "    species = Trim(CStr(cell.Value))\r\n"
    "    ClearAuto cell.Row, ws, cols\r\n"
    "    If Len(species) = 0 Then Exit Sub\r\n"
    "    If Not pLoaded Then LoadUKSI\r\n"
    "    If Not pLoaded Then Exit Sub\r\n"
    "    ' Invalidate own-workbook pending cache (entry changed)\r\n"
    "    pOwnLoaded = False\r\n"
    "    r = ExactMatch(species)\r\n"
    "    If r > 0 Then\r\n"
    "        FillRow cell.Row, ws, r, cols\r\n"
    "        UpdateInfoPanel cell.Row, ws, cols\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    If Len(species) < 3 Then\r\n"
    "        If cols.Exists(H_TVK) Then ws.Cells(cell.Row, cols(H_TVK)).Value = \"?\"\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    FuzzyMatch species, matches, cnt\r\n"
    "    If cnt = 0 Then\r\n"
    "        If cols.Exists(H_TVK) Then ws.Cells(cell.Row, cols(H_TVK)).Value = \"?\"\r\n"
    "    ElseIf cnt = 1 Then\r\n"
    "        FillRow cell.Row, ws, matches(1), cols\r\n"
    "        Application.EnableEvents = False\r\n"
    "        cell.Value = pData(matches(1), U_NAME)\r\n"
    "        Application.EnableEvents = True\r\n"
    "        UpdateInfoPanel cell.Row, ws, cols\r\n"
    "    Else\r\n"
    "        pick = PickSpecies(species, matches, cnt)\r\n"
    "        If pick > 0 Then\r\n"
    "            FillRow cell.Row, ws, pick, cols\r\n"
    "            Application.EnableEvents = False\r\n"
    "            cell.Value = pData(pick, U_NAME)\r\n"
    "            Application.EnableEvents = True\r\n"
    "            UpdateInfoPanel cell.Row, ws, cols\r\n"
    "        Else\r\n"
    "            If cols.Exists(H_TVK) Then ws.Cells(cell.Row, cols(H_TVK)).Value = \"?\"\r\n"
    "        End If\r\n"
    "    End If\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' LOAD UKSI DATA\r\n"
    "' =============================================================\r\n"
    "Private Sub LoadUKSI()\r\n"
    "    Dim wsU As Worksheet\r\n"
    "    On Error Resume Next\r\n"
    "    Set wsU = ThisWorkbook.Sheets(\"UKSI\")\r\n"
    "    On Error GoTo 0\r\n"
    "    If wsU Is Nothing Then Exit Sub\r\n"
    "    Application.StatusBar = \"Loading species data...\"\r\n"
    "    pRows = wsU.Cells(wsU.Rows.Count, 1).End(xlUp).Row - 1\r\n"
    "    If pRows < 1 Then Exit Sub\r\n"
    "    pData = wsU.Range(\"A2:N\" & (pRows + 1)).Value\r\n"
    "    pLoaded = True\r\n"
    "    Application.StatusBar = False\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' LOAD RECORDS INTO DICTIONARY (now with pending columns)\r\n"
    "' =============================================================\r\n"
    "Private Sub LoadRecords()\r\n"
    "    Dim wsR As Worksheet\r\n"
    "    Dim lastRow As Long\r\n"
    "    Dim i As Long\r\n"
    "    Dim tvk As String\r\n"
    "    Dim vals(1 To 7) As Variant\r\n"
    "    Dim ppVal As Variant\r\n"
    "    Dim pcVal As Variant\r\n"
    "\r\n"
    "    Set pRec = CreateObject(\"Scripting.Dictionary\")\r\n"
    "    On Error Resume Next\r\n"
    "    Set wsR = ThisWorkbook.Sheets(\"Records\")\r\n"
    "    On Error GoTo 0\r\n"
    "    If wsR Is Nothing Then\r\n"
    "        pRecLoaded = True\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    lastRow = wsR.Cells(wsR.Rows.Count, 1).End(xlUp).Row\r\n"
    "    If lastRow < 2 Then\r\n"
    "        pRecLoaded = True\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    For i = 2 To lastRow\r\n"
    "        tvk = Trim(CStr(wsR.Cells(i, 1).Value))\r\n"
    "        If Len(tvk) > 0 Then\r\n"
    "            vals(1) = wsR.Cells(i, 2).Value\r\n"
    "            vals(2) = wsR.Cells(i, 3).Value\r\n"
    "            vals(3) = wsR.Cells(i, 4).Value\r\n"
    "            vals(4) = wsR.Cells(i, 5).Value\r\n"
    "            vals(5) = wsR.Cells(i, 6).Value\r\n"
    "            ppVal = wsR.Cells(i, 7).Value\r\n"
    "            pcVal = wsR.Cells(i, 8).Value\r\n"
    "            If IsEmpty(ppVal) Or Len(Trim(CStr(ppVal))) = 0 Then\r\n"
    "                vals(6) = 0\r\n"
    "            Else\r\n"
    "                vals(6) = Val(ppVal)\r\n"
    "            End If\r\n"
    "            If IsEmpty(pcVal) Or Len(Trim(CStr(pcVal))) = 0 Then\r\n"
    "                vals(7) = 0\r\n"
    "            Else\r\n"
    "                vals(7) = Val(pcVal)\r\n"
    "            End If\r\n"
    "            pRec(tvk) = vals\r\n"
    "        End If\r\n"
    "    Next i\r\n"
    "    pRecLoaded = True\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' COUNT OWN WORKBOOK ENTRIES AS PENDING\r\n"
    "' =============================================================\r\n"
    "Private Sub CountOwnPending()\r\n"
    "    Dim sheetNames As Variant\r\n"
    "    Dim slotIndex As Variant\r\n"
    "    Dim idx As Long\r\n"
    "    Dim ws As Worksheet\r\n"
    "    Dim tvk As String\r\n"
    "    Dim slot As Long\r\n"
    "    Dim c As Long\r\n"
    "    Dim lastCol As Long\r\n"
    "    Dim tvkCol As Long\r\n"
    "    Dim lastRow As Long\r\n"
    "    Dim r As Long\r\n"
    "    Dim ev As Variant\r\n"
    "    Dim nv(1 To 2) As Variant\r\n"
    "\r\n"
    "    Set pOwn = CreateObject(\"Scripting.Dictionary\")\r\n"
    "    pOwnLoaded = True\r\n"
    "\r\n"
    "    sheetNames = Array(\"Personal Observations\", \"Commercial Observations\")\r\n"
    "    slotIndex = Array(1, 2)\r\n"
    "\r\n"
    "    For idx = 0 To UBound(sheetNames)\r\n"
    "        Set ws = Nothing\r\n"
    "        On Error Resume Next\r\n"
    "        Set ws = ThisWorkbook.Sheets(CStr(sheetNames(idx)))\r\n"
    "        On Error GoTo 0\r\n"
    "        If ws Is Nothing Then GoTo NextSheet\r\n"
    "\r\n"
    "        tvkCol = 0\r\n"
    "        lastCol = ws.Cells(HDR_ROW, ws.Columns.Count).End(xlToLeft).Column\r\n"
    "        For c = 1 To lastCol\r\n"
    "            If Trim(CStr(ws.Cells(HDR_ROW, c).Value)) = H_TVK Then\r\n"
    "                tvkCol = c\r\n"
    "                Exit For\r\n"
    "            End If\r\n"
    "        Next c\r\n"
    "        If tvkCol = 0 Then GoTo NextSheet\r\n"
    "\r\n"
    "        lastRow = ws.Cells(ws.Rows.Count, tvkCol).End(xlUp).Row\r\n"
    "        For r = DATA_START To lastRow\r\n"
    "            tvk = Trim(CStr(ws.Cells(r, tvkCol).Value))\r\n"
    "            If Len(tvk) > 0 And tvk <> \"?\" Then\r\n"
    "                slot = Val(slotIndex(idx))\r\n"
    "                If pOwn.Exists(tvk) Then\r\n"
    "                    ev = pOwn(tvk)\r\n"
    "                    ev(slot) = Val(ev(slot)) + 1\r\n"
    "                    pOwn(tvk) = ev\r\n"
    "                Else\r\n"
    "                    nv(1) = 0: nv(2) = 0\r\n"
    "                    nv(slot) = 1\r\n"
    "                    pOwn(tvk) = nv\r\n"
    "                End If\r\n"
    "            End If\r\n"
    "        Next r\r\n"
    "\r\n"
    "NextSheet:\r\n"
    "    Next idx\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' FILL AUTO-POPULATE COLUMNS + RECORDS WITH PENDING\r\n"
    "' =============================================================\r\n"
    "Private Sub FillRow(r As Long, ws As Worksheet, uksiRow As Long, cols As Object)\r\n"
    "    Dim tvk As String\r\n"
    "    Dim dbP As Long\r\n"
    "    Dim dbC As Long\r\n"
    "    Dim dbS As Long\r\n"
    "    Dim pendP As Long\r\n"
    "    Dim pendC As Long\r\n"
    "    Dim rv As Variant\r\n"
    "    Dim ov As Variant\r\n"
    "\r\n"
    "    If cols.Exists(H_CONSERV) Then ws.Cells(r, cols(H_CONSERV)).Value = pData(uksiRow, U_CONSERV)\r\n"
    "    If cols.Exists(H_REDLIST) Then ws.Cells(r, cols(H_REDLIST)).Value = pData(uksiRow, U_REDLIST)\r\n"
    "    If cols.Exists(H_RARITY) Then ws.Cells(r, cols(H_RARITY)).Value = pData(uksiRow, U_RARITY)\r\n"
    "    If cols.Exists(H_S41) Then ws.Cells(r, cols(H_S41)).Value = pData(uksiRow, U_S41)\r\n"
    "    If cols.Exists(H_LEGAL) Then ws.Cells(r, cols(H_LEGAL)).Value = pData(uksiRow, U_LEGAL)\r\n"
    "    If cols.Exists(H_BAP) Then ws.Cells(r, cols(H_BAP)).Value = pData(uksiRow, U_BAP)\r\n"
    "    If cols.Exists(H_TVK) Then ws.Cells(r, cols(H_TVK)).Value = pData(uksiRow, U_TVK)\r\n"
    "    If cols.Exists(H_COMMON) Then ws.Cells(r, cols(H_COMMON)).Value = pData(uksiRow, U_COMMON)\r\n"
    "    If cols.Exists(H_CLASS) Then ws.Cells(r, cols(H_CLASS)).Value = pData(uksiRow, U_CLASS)\r\n"
    "    If cols.Exists(H_ORDER) Then ws.Cells(r, cols(H_ORDER)).Value = pData(uksiRow, U_ORDER)\r\n"
    "    If cols.Exists(H_FAMILY) Then ws.Cells(r, cols(H_FAMILY)).Value = pData(uksiRow, U_FAMILY)\r\n"
    "    If cols.Exists(H_SORT) Then ws.Cells(r, cols(H_SORT)).Value = pData(uksiRow, U_SORT)\r\n"
    "\r\n"
    "    ' Records from observatum.db + pending from workbooks\r\n"
    "    If Not pRecLoaded Then LoadRecords\r\n"
    "    If Not pOwnLoaded Then CountOwnPending\r\n"
    "\r\n"
    "    tvk = CStr(pData(uksiRow, U_TVK))\r\n"
    "    dbP = 0: dbC = 0: dbS = 0: pendP = 0: pendC = 0\r\n"
    "\r\n"
    "    If Not pRec Is Nothing Then\r\n"
    "        If pRec.Exists(tvk) Then\r\n"
    "            rv = pRec(tvk)\r\n"
    "            dbP = Val(rv(1))\r\n"
    "            dbC = Val(rv(3))\r\n"
    "            dbS = Val(rv(5))\r\n"
    "            pendP = Val(rv(6))\r\n"
    "            pendC = Val(rv(7))\r\n"
    "        End If\r\n"
    "    End If\r\n"
    "\r\n"
    "    ' Add own-workbook pending\r\n"
    "    If Not pOwn Is Nothing Then\r\n"
    "        If pOwn.Exists(tvk) Then\r\n"
    "            ov = pOwn(tvk)\r\n"
    "            pendP = pendP + Val(ov(1))\r\n"
    "            pendC = pendC + Val(ov(2))\r\n"
    "        End If\r\n"
    "    End If\r\n"
    "\r\n"
    "    ' Display: DB count or \"DB+Np\" if pending\r\n"
    "    If cols.Exists(H_PERSONAL) Then\r\n"
    "        If pendP > 0 Then\r\n"
    "            ws.Cells(r, cols(H_PERSONAL)).Value = CStr(dbP) & \"+\" & CStr(pendP) & \"p\"\r\n"
    "        Else\r\n"
    "            ws.Cells(r, cols(H_PERSONAL)).Value = dbP\r\n"
    "        End If\r\n"
    "    End If\r\n"
    "    If cols.Exists(H_COMMERCIAL) Then\r\n"
    "        If pendC > 0 Then\r\n"
    "            ws.Cells(r, cols(H_COMMERCIAL)).Value = CStr(dbC) & \"+\" & CStr(pendC) & \"p\"\r\n"
    "        Else\r\n"
    "            ws.Cells(r, cols(H_COMMERCIAL)).Value = dbC\r\n"
    "        End If\r\n"
    "    End If\r\n"
    "    If cols.Exists(H_SPECIMENS) Then ws.Cells(r, cols(H_SPECIMENS)).Value = dbS\r\n"
    "End Sub\r\n"
    "\r\n"
    "Private Sub ClearAuto(r As Long, ws As Worksheet, cols As Object)\r\n"
    "    Dim keys As Variant\r\n"
    "    Dim k As Variant\r\n"
    "    keys = Array(H_CONSERV, H_REDLIST, H_RARITY, H_S41, H_LEGAL, H_BAP, _\r\n"
    "                 H_TVK, H_COMMON, H_CLASS, H_ORDER, H_FAMILY, H_SORT, _\r\n"
    "                 H_PERSONAL, H_COMMERCIAL, H_SPECIMENS)\r\n"
    "    For Each k In keys\r\n"
    "        If cols.Exists(CStr(k)) Then ws.Cells(r, cols(CStr(k))).Value = \"\"\r\n"
    "    Next k\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' EXACT MATCH\r\n"
    "' =============================================================\r\n"
    "Private Function ExactMatch(species As String) As Long\r\n"
    "    Dim wsU As Worksheet\r\n"
    "    Dim result As Variant\r\n"
    "    Set wsU = ThisWorkbook.Sheets(\"UKSI\")\r\n"
    "    result = Application.Match(species, wsU.Range(\"A2:A\" & (pRows + 1)), 0)\r\n"
    "    If Not IsError(result) Then\r\n"
    "        ExactMatch = Val(result)\r\n"
    "    Else\r\n"
    "        ExactMatch = 0\r\n"
    "    End If\r\n"
    "End Function\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' FUZZY MATCH\r\n"
    "' =============================================================\r\n"
    "Private Sub FuzzyMatch(searchTerm As String, matches() As Long, cnt As Long)\r\n"
    "    Dim words() As String\r\n"
    "    Dim maxMatches As Long\r\n"
    "    Dim i As Long\r\n"
    "    Dim j As Long\r\n"
    "    Dim combined As String\r\n"
    "    Dim allFound As Boolean\r\n"
    "    words = Split(LCase(Trim(searchTerm)), \" \")\r\n"
    "    maxMatches = 20\r\n"
    "    ReDim matches(1 To maxMatches)\r\n"
    "    cnt = 0\r\n"
    "    For i = 1 To pRows\r\n"
    "        combined = LCase(CStr(pData(i, U_NAME)) & \" \" & CStr(pData(i, U_COMMON)))\r\n"
    "        allFound = True\r\n"
    "        For j = LBound(words) To UBound(words)\r\n"
    "            If Len(words(j)) > 0 Then\r\n"
    "                If InStr(1, combined, words(j), vbTextCompare) = 0 Then\r\n"
    "                    allFound = False\r\n"
    "                    Exit For\r\n"
    "                End If\r\n"
    "            End If\r\n"
    "        Next j\r\n"
    "        If allFound Then\r\n"
    "            cnt = cnt + 1\r\n"
    "            If cnt <= maxMatches Then\r\n"
    "                matches(cnt) = i\r\n"
    "            Else\r\n"
    "                Exit For\r\n"
    "            End If\r\n"
    "        End If\r\n"
    "    Next i\r\n"
    "    If cnt > maxMatches Then cnt = maxMatches\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' SPECIES PICKER\r\n"
    "' =============================================================\r\n"
    "Private Function PickSpecies(searchTerm As String, _\r\n"
    "                             matches() As Long, cnt As Long) As Long\r\n"
    "    Dim maxShow As Long\r\n"
    "    Dim msg As String\r\n"
    "    Dim i As Long\r\n"
    "    Dim common As String\r\n"
    "    Dim fam As String\r\n"
    "    Dim choice As String\r\n"
    "    Dim num As Long\r\n"
    "    maxShow = cnt\r\n"
    "    If maxShow > 15 Then maxShow = 15\r\n"
    "    msg = \"Multiple matches for '\" & searchTerm & \"':\" _\r\n"
    "        & vbCrLf & vbCrLf\r\n"
    "    For i = 1 To maxShow\r\n"
    "        common = CStr(pData(matches(i), U_COMMON))\r\n"
    "        fam = CStr(pData(matches(i), U_FAMILY))\r\n"
    "        msg = msg & i & \".  \" & pData(matches(i), U_NAME)\r\n"
    "        If Len(common) > 0 Then msg = msg & \"  (\" & common & \")\"\r\n"
    "        If Len(fam) > 0 Then msg = msg & \"  [\" & fam & \"]\"\r\n"
    "        msg = msg & vbCrLf\r\n"
    "    Next i\r\n"
    "    If cnt > 15 Then\r\n"
    "        msg = msg & vbCrLf & \"(\" & (cnt - 15) _\r\n"
    "            & \" more matches not shown. Refine your search.)\"\r\n"
    "    End If\r\n"
    "    msg = msg & vbCrLf & \"Enter number (1-\" & maxShow _\r\n"
    "        & \"), or 0 to cancel:\"\r\n"
    "    choice = InputBox(msg, \"Species Lookup\")\r\n"
    "    If Len(choice) = 0 Then\r\n"
    "        PickSpecies = 0\r\n"
    "        Exit Function\r\n"
    "    End If\r\n"
    "    On Error Resume Next\r\n"
    "    num = Val(choice)\r\n"
    "    On Error GoTo 0\r\n"
    "    If num >= 1 And num <= maxShow Then\r\n"
    "        PickSpecies = matches(num)\r\n"
    "    Else\r\n"
    "        PickSpecies = 0\r\n"
    "    End If\r\n"
    "End Function\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' REFRESH RECORDS -- shells out to Python, reloads Records sheet\r\n"
    "' =============================================================\r\n"
    "Public Sub RefreshRecords()\r\n"
    "    Dim wsI As Worksheet\r\n"
    "    Dim pyPath As String\r\n"
    "    Dim script As String\r\n"
    "    Dim csvPath As String\r\n"
    "    Dim wsh As Object\r\n"
    "    Dim cmd As String\r\n"
    "    Dim rc As Long\r\n"
    "\r\n"
    "    On Error Resume Next\r\n"
    "    Set wsI = ThisWorkbook.Sheets(\"Instructions\")\r\n"
    "    On Error GoTo 0\r\n"
    "    If wsI Is Nothing Then\r\n"
    "        MsgBox \"Instructions sheet not found.\", vbExclamation, \"Tabella\"\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    pyPath = Trim(CStr(wsI.Cells(100, 1).Value))\r\n"
    "    If Len(pyPath) = 0 Then pyPath = \"python\"\r\n"
    "    script = Trim(CStr(wsI.Cells(101, 1).Value))\r\n"
    "    csvPath = Trim(CStr(wsI.Cells(102, 1).Value))\r\n"
    "    If Len(script) = 0 Or Len(csvPath) = 0 Then\r\n"
    "        MsgBox \"Paths not found in Instructions sheet.\" & vbCrLf _\r\n"
    "            & \"Please regenerate the workbook.\", vbExclamation, \"Tabella\"\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    Application.StatusBar = \"Refreshing records from database and workbooks...\"\r\n"
    "    Set wsh = CreateObject(\"WScript.Shell\")\r\n"
    "    ' Pass --skip with our own path so refresh_records.py excludes\r\n"
    "    ' this workbook -- CountOwnPending covers it live, no double count.\r\n"
    "    cmd = Chr(34) & pyPath & Chr(34) & \" \" & Chr(34) & script & Chr(34) & _\r\n"
    "          \" --skip \" & Chr(34) & ThisWorkbook.FullName & Chr(34)\r\n"
    "    rc = wsh.Run(cmd, 0, True)\r\n"
    "    If rc <> 0 Then\r\n"
    "        Application.StatusBar = False\r\n"
    "        MsgBox \"Records refresh failed (exit code \" & rc & \").\" & vbCrLf _\r\n"
    "            & \"Check that Python and the database are available.\", _\r\n"
    "            vbExclamation, \"Tabella\"\r\n"
    "        Exit Sub\r\n"
    "    End If\r\n"
    "    LoadRecordsCSV csvPath\r\n"
    "    ' Reset all caches so new data is picked up\r\n"
    "    pRecLoaded = False\r\n"
    "    pOwnLoaded = False\r\n"
    "    LoadRecords\r\n"
    "    CountOwnPending\r\n"
    "    Application.StatusBar = False\r\n"
    "    MsgBox \"Records refreshed successfully.\" & vbCrLf _\r\n"
    "        & \"Pending counts include entries from active workbooks.\", _\r\n"
    "        vbInformation, \"Tabella\"\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' PARSE CSV LINE -- quote-aware, handles embedded commas\r\n"
    "' Fix (May 2026): replaces naive Split which corrupted records\r\n"
    "' for any species with multiple commercial projects.\r\n"
    "' =============================================================\r\n"
    "Private Sub ParseCSVLine(line As String, fields() As String, _\r\n"
    "                        ByRef nFields As Long)\r\n"
    "    Dim i As Long\r\n"
    "    Dim L As Long\r\n"
    "    Dim ch As String\r\n"
    "    Dim field As String\r\n"
    "    Dim inQuotes As Boolean\r\n"
    "    Dim QUOTE As String\r\n"
    "    QUOTE = Chr(34)\r\n"
    "    L = Len(line)\r\n"
    "    ReDim fields(0 To 50)\r\n"
    "    nFields = 0\r\n"
    "    field = \"\"\r\n"
    "    inQuotes = False\r\n"
    "    i = 1\r\n"
    "    Do While i <= L\r\n"
    "        ch = Mid(line, i, 1)\r\n"
    "        If inQuotes Then\r\n"
    "            If ch = QUOTE Then\r\n"
    "                If i < L Then\r\n"
    "                    If Mid(line, i + 1, 1) = QUOTE Then\r\n"
    "                        ' Escaped quote inside quoted field\r\n"
    "                        field = field & QUOTE\r\n"
    "                        i = i + 1\r\n"
    "                    Else\r\n"
    "                        inQuotes = False\r\n"
    "                    End If\r\n"
    "                Else\r\n"
    "                    inQuotes = False\r\n"
    "                End If\r\n"
    "            Else\r\n"
    "                field = field & ch\r\n"
    "            End If\r\n"
    "        Else\r\n"
    "            If ch = QUOTE Then\r\n"
    "                inQuotes = True\r\n"
    "            ElseIf ch = \",\" Then\r\n"
    "                fields(nFields) = field\r\n"
    "                nFields = nFields + 1\r\n"
    "                field = \"\"\r\n"
    "            Else\r\n"
    "                field = field & ch\r\n"
    "            End If\r\n"
    "        End If\r\n"
    "        i = i + 1\r\n"
    "    Loop\r\n"
    "    fields(nFields) = field\r\n"
    "    nFields = nFields + 1\r\n"
    "End Sub\r\n"
    "\r\n"
    "\r\n"
    "' =============================================================\r\n"
    "' LOAD RECORDS CSV INTO SHEET (8 columns, quote-aware)\r\n"
    "' =============================================================\r\n"
    "Private Sub LoadRecordsCSV(csvPath As String)\r\n"
    "    Dim wsR As Worksheet\r\n"
    "    Dim lastR As Long\r\n"
    "    Dim fn As Integer\r\n"
    "    Dim openErr As Long\r\n"
    "    Dim lineText As String\r\n"
    "    Dim r As Long\r\n"
    "    Dim fields() As String\r\n"
    "    Dim nFields As Long\r\n"
    "    Dim c As Long\r\n"
    "\r\n"
    "    On Error Resume Next\r\n"
    "    Set wsR = ThisWorkbook.Sheets(\"Records\")\r\n"
    "    On Error GoTo 0\r\n"
    "    If wsR Is Nothing Then Exit Sub\r\n"
    "    ' Clear data rows (row 2 onward)\r\n"
    "    lastR = wsR.Cells(wsR.Rows.Count, 1).End(xlUp).Row\r\n"
    "    If lastR >= 2 Then\r\n"
    "        wsR.Range(\"A2:H\" & lastR).ClearContents\r\n"
    "    End If\r\n"
    "    ' Open the CSV file\r\n"
    "    fn = FreeFile\r\n"
    "    Err.Clear\r\n"
    "    On Error Resume Next\r\n"
    "    Open csvPath For Input As #fn\r\n"
    "    openErr = Err.Number\r\n"
    "    On Error GoTo 0\r\n"
    "    If openErr <> 0 Then Exit Sub\r\n"
    "    ' Read line by line, parsing each via ParseCSVLine\r\n"
    "    r = 1\r\n"
    "    If Not EOF(fn) Then Line Input #fn, lineText\r\n"
    "    Do While Not EOF(fn)\r\n"
    "        r = r + 1\r\n"
    "        Line Input #fn, lineText\r\n"
    "        ParseCSVLine lineText, fields, nFields\r\n"
    "        For c = 0 To nFields - 1\r\n"
    "            If c < 8 Then wsR.Cells(r, c + 1).Value = fields(c)\r\n"
    "        Next c\r\n"
    "    Loop\r\n"
    "    Close #fn\r\n"
    "End Sub\r\n"
)
